name: Publish Docker image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.17.0, 0.18.0, 0.19.0, 0.20.0]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set image tag
        id: tag
        run: |
          latest=$(cat thrift/VERSION)
          image_name="khaledez/thrift"
          tags="${image_name}:${{ matrix.version }}"
          if [ "$latest" = "${{ matrix.version }}" ]; then
            tags="$tags, $image_name:latest"
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Build and push thrift
        uses: docker/build-push-action@v5
        with:
          context: thrift
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: THRIFT_VERSION=v${{ matrix.version }}
          tags: ${{ steps.tag.outputs.tags }}
